# add the following to _config.yml file
title: Sharath Diwakar
#description: [A short description of your site's purpose]
#remote_theme: pages-themes/minimal@v0.2.0
theme: minima
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#show_downloads: true
