title: Sharath Diwakar
logo: /assets/img/logo.png
description: Data conossieur helping companies generate business from their data
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
